#!/bin/bash

# Canary Deployment Script for CHOM
# Gradually shifts traffic from old to new version with monitoring

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
DEPLOYMENT_LOG="/var/log/chom/canary_deployment_${TIMESTAMP}.log"

# Configuration
APP_PATH="${APP_PATH:-/var/www/chom}"
RELEASES_PATH="${RELEASES_PATH:-/var/www/releases}"
VERSION="${VERSION:-${TIMESTAMP}}"
ARTIFACT_PATH="${ARTIFACT_PATH:-}"

# Canary configuration
CANARY_STAGES="${CANARY_STAGES:-10,25,50,75,100}"
CANARY_INTERVAL="${CANARY_INTERVAL:-300}"  # 5 minutes between stages
ERROR_RATE_THRESHOLD="${ERROR_RATE_THRESHOLD:-5.0}"  # Max 5% error rate
RESPONSE_TIME_THRESHOLD="${RESPONSE_TIME_THRESHOLD:-2000}"  # Max 2000ms

# Nginx upstream configuration
NGINX_UPSTREAM_CONF="/etc/nginx/conf.d/upstream.conf"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$DEPLOYMENT_LOG"
}

log_success() {
    echo -e "${GREEN}[$(date '+%Y-%m-%d %H:%M:%S')] ✓ $1${NC}" | tee -a "$DEPLOYMENT_LOG"
}

log_error() {
    echo -e "${RED}[$(date '+%Y-%m-%d %H:%M:%S')] ✗ $1${NC}" | tee -a "$DEPLOYMENT_LOG"
}

log_warning() {
    echo -e "${YELLOW}[$(date '+%Y-%m-%d %H:%M:%S')] ⚠ $1${NC}" | tee -a "$DEPLOYMENT_LOG"
}

log_info() {
    echo -e "${BLUE}[$(date '+%Y-%m-%d %H:%M:%S')] ℹ $1${NC}" | tee -a "$DEPLOYMENT_LOG"
}

# Update Nginx upstream weights
update_traffic_weight() {
    local canary_weight=$1
    local stable_weight=$((100 - canary_weight))

    log_info "Updating traffic: Stable=${stable_weight}%, Canary=${canary_weight}%"

    cat > "${NGINX_UPSTREAM_CONF}" <<EOF
# Generated by canary deployment at $(date)
upstream chom_backend {
    server unix:/run/php/chom-stable.sock weight=${stable_weight};
    server unix:/run/php/chom-canary.sock weight=${canary_weight};

    keepalive 32;
}
EOF

    nginx -t && nginx -s reload
    log_success "Traffic distribution updated"
}

# Monitor canary metrics
check_canary_metrics() {
    local duration=$1

    log_info "Monitoring canary metrics for ${duration} seconds..."

    # Query Prometheus for error rate (requires Prometheus API)
    if [ -n "${PROMETHEUS_URL:-}" ]; then
        ERROR_RATE=$(curl -s "${PROMETHEUS_URL}/api/v1/query" \
            --data-urlencode "query=rate(http_requests_total{status=~\"5..\",version=\"${VERSION}\"}[5m])*100" \
            | jq -r '.data.result[0].value[1] // "0"')

        AVG_RESPONSE_TIME=$(curl -s "${PROMETHEUS_URL}/api/v1/query" \
            --data-urlencode "query=histogram_quantile(0.95, http_request_duration_seconds{version=\"${VERSION}\"})*1000" \
            | jq -r '.data.result[0].value[1] // "0"')

        log_info "Canary error rate: ${ERROR_RATE}%"
        log_info "Canary p95 response time: ${AVG_RESPONSE_TIME}ms"

        # Check thresholds
        if (( $(echo "$ERROR_RATE > $ERROR_RATE_THRESHOLD" | bc -l) )); then
            log_error "Error rate ${ERROR_RATE}% exceeds threshold ${ERROR_RATE_THRESHOLD}%"
            return 1
        fi

        if (( $(echo "$AVG_RESPONSE_TIME > $RESPONSE_TIME_THRESHOLD" | bc -l) )); then
            log_error "Response time ${AVG_RESPONSE_TIME}ms exceeds threshold ${RESPONSE_TIME_THRESHOLD}ms"
            return 1
        fi

        log_success "Metrics within acceptable thresholds"
    else
        log_warning "Prometheus not configured, skipping automated metrics check"
        sleep $duration
    fi

    return 0
}

# Rollback to stable version
rollback_canary() {
    log_warning "========================================="
    log_warning "  CANARY ROLLBACK INITIATED"
    log_warning "========================================="

    # Route 100% traffic to stable
    update_traffic_weight 0

    # Stop canary PHP-FPM pool
    systemctl stop php8.2-fpm-canary || true

    log_success "Rollback completed - 100% traffic on stable version"
}

error_handler() {
    log_error "Deployment failed at line $1"
    rollback_canary
    exit 1
}

trap 'error_handler $LINENO' ERR

log_info "========================================="
log_info "  CANARY DEPLOYMENT STARTED"
log_info "========================================="
log_info "Version: ${VERSION}"
log_info "Stages: ${CANARY_STAGES}"
log_info "Interval: ${CANARY_INTERVAL}s"

# Step 1: Deploy canary version
log_info "Step 1: Deploying canary version..."
CANARY_PATH="${RELEASES_PATH}/${VERSION}-canary"
mkdir -p "${CANARY_PATH}"

if [ -n "$ARTIFACT_PATH" ] && [ -f "$ARTIFACT_PATH" ]; then
    tar -xzf "${ARTIFACT_PATH}" -C "${CANARY_PATH}"
else
    log_error "Artifact not found: ${ARTIFACT_PATH}"
    exit 1
fi

# Configure canary
cp "${APP_PATH}/.env" "${CANARY_PATH}/.env"
rm -rf "${CANARY_PATH}/storage"
ln -sfn "/var/www/shared/storage" "${CANARY_PATH}/storage"
chown -R www-data:www-data "${CANARY_PATH}"

# Optimize canary
cd "${CANARY_PATH}"
sudo -u www-data php artisan config:cache
sudo -u www-data php artisan route:cache
sudo -u www-data php artisan view:cache

log_success "Canary version deployed"

# Step 2: Create separate PHP-FPM pool for canary
log_info "Step 2: Creating canary PHP-FPM pool..."

cat > "/etc/php/8.2/fpm/pool.d/canary.conf" <<EOF
[chom-canary]
user = www-data
group = www-data
listen = /run/php/chom-canary.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

pm = dynamic
pm.max_children = 10
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

php_admin_value[error_log] = /var/log/php-fpm/canary-error.log
php_admin_flag[log_errors] = on

env[APP_VERSION] = ${VERSION}
env[DEPLOYMENT_TYPE] = canary
EOF

systemctl restart php8.2-fpm
log_success "Canary PHP-FPM pool created"

# Step 3: Configure stable version socket (if not exists)
if [ ! -f "/etc/php/8.2/fpm/pool.d/stable.conf" ]; then
    log_info "Configuring stable PHP-FPM pool..."

    cat > "/etc/php/8.2/fpm/pool.d/stable.conf" <<EOF
[chom-stable]
user = www-data
group = www-data
listen = /run/php/chom-stable.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

pm = dynamic
pm.max_children = 20
pm.start_servers = 5
pm.min_spare_servers = 2
pm.max_spare_servers = 10
EOF

    systemctl restart php8.2-fpm
fi

# Step 4: Gradual traffic shift
log_info "Step 4: Beginning gradual traffic shift..."

IFS=',' read -ra STAGES <<< "$CANARY_STAGES"

for stage in "${STAGES[@]}"; do
    log_info "========================================="
    log_info "  Canary Stage: ${stage}%"
    log_info "========================================="

    # Update traffic distribution
    update_traffic_weight "$stage"

    # Monitor period
    if ! check_canary_metrics "$CANARY_INTERVAL"; then
        log_error "Canary metrics check failed at ${stage}% stage"
        rollback_canary
        exit 1
    fi

    log_success "Stage ${stage}% completed successfully"

    if [ "$stage" -lt 100 ]; then
        log_info "Waiting ${CANARY_INTERVAL}s before next stage..."
        sleep "$CANARY_INTERVAL"
    fi
done

# Step 5: Finalize deployment
log_info "Step 5: Finalizing canary deployment..."

# Move canary to stable
STABLE_PATH="${RELEASES_PATH}/${VERSION}"
mv "${CANARY_PATH}" "${STABLE_PATH}"

# Update main symlink
ln -sfn "${STABLE_PATH}" "${APP_PATH}_current"
ln -sfn "${APP_PATH}_current" "${APP_PATH}"

# Switch to single pool
cat > "${NGINX_UPSTREAM_CONF}" <<EOF
# Generated by canary deployment at $(date)
upstream chom_backend {
    server unix:/run/php/www.sock;
    keepalive 32;
}
EOF

nginx -t && nginx -s reload

# Remove canary pool
rm -f "/etc/php/8.2/fpm/pool.d/canary.conf"
systemctl reload php8.2-fpm

log_success "Canary deployment finalized"

# Cleanup
log_info "Cleaning up old releases..."
cd "${RELEASES_PATH}"
ls -t | grep -v "^${VERSION}$" | tail -n +5 | xargs -r rm -rf

log_info "========================================="
log_info "  CANARY DEPLOYMENT COMPLETED"
log_info "========================================="
log_info "Version: ${VERSION}"
log_info "Duration: ${SECONDS} seconds"
log_success "Canary deployment finished! 🚀"

exit 0
