#!/bin/bash
#===============================================================================
# Auto-Detection Script
# Scans the current host for installed services and suggests applicable modules
#
# Usage:
#   ./auto-detect.sh [--generate] [--output hostname.yaml]
#
# Options:
#   --generate    Generate a host config file with detected modules
#   --output      Specify output file path (default: stdout)
#   --quiet       Only output the config, no interactive prompts
#===============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/common.sh"
source "$SCRIPT_DIR/lib/module-loader.sh"

# Options
GENERATE=false
OUTPUT_FILE=""
QUIET=false

# Parse arguments with proper shift handling
while [[ $# -gt 0 ]]; do
    case "$1" in
        --generate|-g)
            GENERATE=true
            shift
            ;;
        --quiet|-q)
            QUIET=true
            shift
            ;;
        --output=*)
            OUTPUT_FILE="${1#*=}"
            shift
            ;;
        --output|-o)
            if [[ -n "${2:-}" ]] && [[ ! "${2:-}" =~ ^- ]]; then
                OUTPUT_FILE="$2"
                shift 2
            else
                echo "Error: --output requires a value"
                exit 1
            fi
            ;;
        --help|-h)
            echo "Usage: $0 [--generate] [--output file] [--quiet]"
            echo ""
            echo "Options:"
            echo "  --generate, -g    Generate host configuration file"
            echo "  --output FILE, -o Specify output file path"
            echo "  --quiet, -q       Quiet mode, minimal output"
            echo "  --help, -h        Show this help message"
            exit 0
            ;;
        -*)
            echo "Error: Unknown option: $1"
            exit 1
            ;;
        *)
            echo "Error: Unexpected argument: $1"
            exit 1
            ;;
    esac
done

#===============================================================================
# DETECTION
#===============================================================================

detect_modules() {
    local results=()

    log_info "Scanning host for installed services..."
    echo ""

    while IFS= read -r module; do
        local confidence
        local display_name
        local description

        display_name=$(module_display_name "$module")
        description=$(module_description "$module")

        if confidence=$(module_detect "$module" 2>/dev/null); then
            results+=("$module:$confidence")

            if [[ "$QUIET" != "true" ]]; then
                local color="$GREEN"
                [[ $confidence -lt 80 ]] && color="$YELLOW"
                [[ $confidence -lt 50 ]] && color="$RED"

                printf "  ${color}[%3d%%]${NC} %-25s %s\n" \
                    "$confidence" \
                    "${display_name:-$module}" \
                    "${description:-}"
            fi
        else
            if [[ "$QUIET" != "true" ]]; then
                printf "  ${RED}[  0%%]${NC} %-25s (not detected)\n" \
                    "${display_name:-$module}"
            fi
        fi
    done < <(list_all_modules)

    echo ""

    # Sort by confidence and return
    printf '%s\n' "${results[@]}" | sort -t: -k2 -rn
}

generate_config() {
    local detected_modules="$1"
    local hostname
    hostname=$(hostname -f 2>/dev/null || hostname)
    local host_ip
    host_ip=$(hostname -I | awk '{print $1}')

    cat << EOF
# Host Configuration
# Auto-generated by auto-detect.sh on $(date)

host:
  name: "${hostname%%.*}"
  ip: "$host_ip"
  description: "$hostname"
  environment: "production"
  labels:
    tier: "unknown"

modules:
EOF

    # Generate module entries
    while IFS= read -r module_entry; do
        [[ -z "$module_entry" ]] && continue

        local module="${module_entry%%:*}"
        local confidence="${module_entry#*:}"

        # Only enable modules with confidence > 50
        local enabled="true"
        [[ $confidence -lt 50 ]] && enabled="false"

        cat << EOF
  $module:
    enabled: $enabled
EOF

        # Add module-specific config hints
        case "$module" in
            mysqld_exporter)
                cat << EOF
    config:
      credentials:
        username: "exporter"
        password: "CHANGE_ME"
      host: "127.0.0.1"
      port: 3306
EOF
                ;;
            promtail)
                cat << EOF
    config:
      loki_url: "https://mentat.arewel.com"
      loki_user: "loki"
      loki_password: "CHANGE_ME"
EOF
                ;;
            nginx_exporter)
                cat << EOF
    config:
      stub_status_url: ""
EOF
                ;;
        esac

        echo ""
    done <<< "$detected_modules"
}

#===============================================================================
# INTERACTIVE MODE
#===============================================================================

interactive_config() {
    local detected_modules="$1"

    echo ""
    log_info "Interactive Configuration"
    echo "=========================="
    echo ""
    echo "The following modules were detected. Press Enter to accept defaults"
    echo "or enter 'n' to disable a module."
    echo ""

    local enabled_modules=()

    while IFS= read -r module_entry; do
        [[ -z "$module_entry" ]] && continue

        local module="${module_entry%%:*}"
        local confidence="${module_entry#*:}"
        local display_name
        display_name=$(module_display_name "$module")

        local default="Y"
        [[ $confidence -lt 50 ]] && default="n"

        read -p "  Enable ${display_name:-$module}? [$default] " -n 1 -r response
        echo

        response="${response:-$default}"
        if [[ "$response" =~ ^[Yy]$ ]]; then
            enabled_modules+=("$module:$confidence")
        fi
    done <<< "$detected_modules"

    echo ""
    printf '%s\n' "${enabled_modules[@]}"
}

#===============================================================================
# MAIN
#===============================================================================

main() {
    if [[ "$QUIET" != "true" ]]; then
        echo ""
        echo "========================================"
        echo "Module Auto-Detection"
        echo "========================================"
        echo ""
        echo "Host: $(hostname)"
        echo ""
    fi

    # Detect modules
    local detected
    detected=$(detect_modules)

    if [[ -z "$detected" ]]; then
        log_warn "No modules detected on this host"
        echo ""
        echo "This could mean:"
        echo "  1. No supported services are installed (nginx, mysql, php-fpm, etc.)"
        echo "  2. Services are installed but not running"
        echo "  3. Detection scripts need to be updated for your environment"
        echo ""
        echo "To install monitoring for basic system metrics anyway:"
        echo "  module-manager.sh install node_exporter"
        echo ""
        echo "To see all available modules:"
        echo "  module-manager.sh list"
        exit 1
    fi

    # Interactive mode if not quiet
    if [[ "$QUIET" != "true" ]] && [[ "$GENERATE" == "true" ]] && [[ -z "$OUTPUT_FILE" ]]; then
        detected=$(interactive_config "$detected")
    fi

    # Generate config
    if [[ "$GENERATE" == "true" ]]; then
        local config
        config=$(generate_config "$detected")

        if [[ -n "$OUTPUT_FILE" ]]; then
            echo "$config" > "$OUTPUT_FILE"
            log_success "Configuration written to: $OUTPUT_FILE"
        else
            echo ""
            echo "Generated Configuration:"
            echo "========================"
            echo ""
            echo "$config"
        fi
    else
        if [[ "$QUIET" != "true" ]]; then
            echo ""
            log_info "To generate a host config file, run:"
            echo "  $0 --generate --output=config/hosts/\$(hostname).yaml"
            echo ""
        fi
    fi
}

main "$@"
